#
# An environment for compiling MinGW64 Windows builds
#
#

FROM ubuntu:xenial
MAINTAINER H. Birch Tree

RUN apt-get -qy update && apt-get -qy install \
        git nano wget \
        mercurial \
        cmake ninja-build \
        build-essential

RUN groupadd coffeeusers -g 1000
RUN useradd coffee -m -u 1000

# Set up base directories for building
USER coffee
WORKDIR /home/coffee
RUN mkdir -p project bridge build/bin build/libs build/out
USER root

# Check out source for SDL2 2.0.4
RUN mkdir -p /dependencies/SDL/build
RUN mkdir -p /dependencies/SDL/source
RUN hg clone https://hg.libsdl.org/SDL /dependencies/SDL/source

# Check out source for openal-soft
RUN mkdir -p /dependencies/openal/build
RUN mkdir -p /dependencies/openal/source
RUN git clone https://github.com/kcat/openal-soft.git /dependencies/openal/source

# Check out source for MinGW-W64, because Ubuntu's version is shit
RUN mkdir -p /mingw/build
RUN mkdir -p /mingw/source
RUN git clone git://git.code.sf.net/p/mingw-w64/mingw-w64 /mingw/source

WORKDIR /home/coffee
USER coffee

VOLUME ["/home/coffee/project","/home/coffee/build/libs","/home/coffee/build/out"]
