version: '2'

services:
    raspberry_builder_64:
        build:
            context: ./
            args:
                RASPBERRY_TOOLCHAIN: gcc-linaro-arm-linux-gnueabihf-raspbian-x64
                TOOLCHAIN_NAME: aarch64-raspberry
        environment:
          - ./rpi_sdk_64:/raspi-sdk

    raspberry_builder_32:
        build:
            context: ./
        environment:
          - ./rpi_sdk_32:/raspi-sdk
