ubuntu-builder:
  build: ubuntu/
  hostname: ubuntu-builder

steamos-builder:
  build: steam/
  hostname: steamos-builder

android-builder:
  build: android/
  hostname: android-builder

raspberry-builder:
  build: raspberry
  hostname raspberry-builder

doc-builder:
  build: doc-generator/
  hostname: doc-builder
  volumes:
   - /var/www:/doc-out
