name: Build toolchains
'on':
    push:
        branches:
            - master

jobs:
    Ubuntu:
        runs-on: ubuntu-latest
        env:
            CTNG: '${{ github.workspace }}/crosstool-ng-master/ct-ng'
        strategy:
            matrix:
                system:
                    - name: beaglebone
                      arch: arm-unknown-linux-gnueabihf
                    - name: raspberry
                      arch: arm-unknown-linux-gnueabihf
                    - name: ubuntu
                      arch: x86_64-unknown-linux-gnu
        steps:
            - uses: actions/checkout@v2
              with:
                  path: source
            - name: Download dependencies
              run: sudo apt install -y build-essential flex bison help2man libtool-bin
            - name: Download crosstool-ng
              run: |
                  wget https://github.com/crosstool-ng/crosstool-ng/archive/master.tar.gz
                  tar xvf master.tar.gz
            - name: Install crosstool-ng
              working-directory: ${{ github.workspace }}/crosstool-ng-master
              run: |
                  ./bootstrap
                  ./configure --enable-local
                  make -j4
            - name: Build toolchain
              working-directory: ${{ github.workspace }}/source/toolchains/${{ matrix.system.name }}-ct/compiler
              run: |
                  $CTNG build.4
            - name: Create toolchain artifact
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.system.name }}-${{ matrix.system.arch }}
                  path: ${{ github.workspace }}/source/toolchains/${{ matrix.system.name }}-ct/compiler/${{ matrix.system.arch }}/*
            - name: Build sysroot
              if: false
              working-directory: ${{ github.workspace }}/source/toolchains
              run: |
                  make ${{ matrix.system }}.sysroot
